CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID UNIQUE REFERENCES auth.users(id) ON DELETE CASCADE, -- Link to Supabase auth user
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    field_of_study TEXT,
    year_of_study INTEGER NOT NULL CHECK (year_of_study > 0),
    avatar_url TEXT, -- Add this line to store the public URL of the avatar
    created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optional: Add comments to describe the table and columns
COMMENT ON TABLE public.students IS 'Stores information about students.';
COMMENT ON COLUMN public.students.user_id IS 'Foreign key linking to the Supabase auth user.';
COMMENT ON COLUMN public.students.name IS 'Full name of the student.';
COMMENT ON COLUMN public.students.email IS 'Unique email address of the student.';
COMMENT ON COLUMN public.students.field_of_study IS 'The student''s field of study.';
COMMENT ON COLUMN public.students.year_of_study IS 'Current year of study (e.g., 1, 2, 3).';
COMMENT ON COLUMN public.students.avatar_url IS 'Public URL of the student''s avatar image in Supabase Storage.'; -- Add this comment
COMMENT ON COLUMN public.students.created_at IS 'Timestamp when the student record was created.';